<script setup>
import {onMounted,ref} from 'vue'
import {apiJson} from '../api/client.js'
const rows=ref([]),offset=ref(0),total=ref(0),busy=ref(false),error=ref(''),source=ref(''),text=ref(''),versions=ref(null)
const request=(path,opts)=>apiJson('/api/v1/admin'+path,opts)
async function load(){try{const data=await request('/knowledge-jobs?offset='+offset.value);rows.value=data.items;total.value=data.total}catch(e){error.value=e.message}}
async function create(){if(busy.value)return;busy.value=true;error.value='';try{await request('/knowledge-jobs',{method:'POST',body:JSON.stringify({source:source.value,text:text.value})});source.value='';text.value='';offset.value=0;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function run(id){if(busy.value)return;busy.value=true;error.value='';try{await request(`/knowledge-jobs/${id}/run`,{method:'POST'});versions.value=await request('/knowledge-versions')}catch(e){error.value=e.message}finally{await load();busy.value=false}}
async function showVersions(){try{versions.value=await request('/knowledge-versions')}catch(e){error.value=e.message}}
async function rollback(version){if(busy.value||!confirm('确认切换到此知识版本？当前版本会保留。'))return;busy.value=true;try{await request('/knowledge-versions/rollback',{method:'POST',body:JSON.stringify({version})});await showVersions()}catch(e){error.value=e.message}finally{busy.value=false}}
async function file(event){const value=event.target.files[0];if(!value)return;if(value.size>1000000){error.value='文件最多 1 MB';return}source.value=value.name;text.value=await value.text();event.target.value=''}
onMounted(load)
</script>
<template><section class="jobs"><p>上传 TXT / Markdown 或粘贴文本。相同来源名称替换该来源，其余资料保留。先创建任务，再执行导入。</p><form @submit.prevent="create"><label>来源名称<input v-model="source" maxlength="100" required></label><label>选择文本文件<input type="file" accept=".txt,.md" @change="file"></label><label>源文本<textarea v-model="text" maxlength="1000000" required></textarea></label><button :disabled="busy||!text.trim()||!source.trim()">创建导入任务</button></form><p v-if="error" role="alert">{{ error }}</p><button :disabled="busy" @click="load">刷新任务</button><button :disabled="busy" @click="showVersions">查看知识版本</button><article v-for="job in rows" :key="job.id"><h2>{{ job.source }}</h2><p>{{ {queued:'待执行',building:'构建中',completed:'已完成',failed:'失败，可重试'}[job.status] }} · {{ job.updated_at }}</p><p>{{ job.error }}</p><button v-if="['queued','failed'].includes(job.status)" :disabled="busy" @click="run(job.id)">{{ job.status==='failed'?'重试任务':'执行导入' }}</button></article><footer><button :disabled="busy||!offset" @click="offset-=20;load()">上一页</button><button :disabled="busy||offset+20>=total" @click="offset+=20;load()">下一页</button></footer><section v-if="versions"><h2>知识版本</h2><article v-for="version in versions.items" :key="version"><p>{{ version }}</p><span v-if="versions.active===version">当前版本</span><button v-else :disabled="busy" @click="rollback(version)">切换至此版本</button></article></section></section></template>
<style scoped>.jobs{line-height:1.8;overflow-wrap:anywhere}.jobs form,.jobs article{background:white;border:1px solid var(--line);border-radius:14px;padding:20px;margin:16px 0}.jobs label{display:block}.jobs input,.jobs textarea{display:block;padding:10px;width:100%;font:inherit;border:1px solid var(--line);border-radius:8px;margin:8px 0}.jobs textarea{min-height:150px}.jobs button{font:inherit;padding:9px 12px;background:white;color:var(--ink);border:1px solid var(--line);border-radius:8px;margin:5px;cursor:pointer}.jobs h2{font-size:16px}</style>
