import {test,expect} from '@playwright/test'

test('多宠物创建编辑、关联发布、公开主页与删除保留帖子',async({page})=>{
  let pets=[],posts=[],nextId=1
  const author={id:1,name:'小林',avatar_id:''}, photo='a'.repeat(32)
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.addInitScript(()=>{sessionStorage.setItem('token','test');sessionStorage.setItem('username','alice')})
  await page.route('**/api/v1/**',async route=>{
    const req=route.request(),url=new URL(req.url()),path=url.pathname
    const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'*'}
    const json=(data,status=200)=>route.fulfill({headers,status,contentType:'application/json',body:JSON.stringify(data)})
    if(req.method()==='OPTIONS')return route.fulfill({status:204,headers})
    if(path.endsWith('/auth/me'))return json({id:1,username:'alice',nickname:'小林',role:'user'})
    if(path.endsWith('/media')&&req.method()==='POST')return json({id:photo})
    if(path.includes('/photo/')||path.includes('/media/'))return route.fulfill({headers,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=','base64')})
    if(path.endsWith('/me/pets')){
      if(req.method()==='POST'){const pet={...req.postDataJSON(),id:nextId++,version:1};pets.push(pet);return json(pet,201)}
      return json({items:pets})
    }
    const own=path.match(/\/me\/pets\/(\d+)$/)
    if(own){const id=Number(own[1]),pet=pets.find(p=>p.id===id);if(req.method()==='DELETE'){pets=pets.filter(p=>p.id!==id);posts.forEach(p=>{p.pet_ids=p.pet_ids.filter(i=>i!==id)});return json({success:true})}Object.assign(pet,req.postDataJSON(),{version:pet.version+1});return json(pet)}
    if(path.endsWith('/users/1'))return json({...author,bio:'分享日常',post_count:posts.length,pets})
    const petId=Number(path.match(/\/pets\/(\d+)(?:\/posts)?$/)?.[1])
    if(petId){const pet=pets.find(p=>p.id===petId);if(!pet)return json({detail:'宠物档案不可用'},404);const items=posts.filter(p=>p.pet_ids.includes(petId));return json(path.endsWith('/posts')?{items,next_cursor:null}:{...pet,owner:author,post_count:items.length})}
    if(path.endsWith('/posts')&&req.method()==='POST'){const post={...req.postDataJSON(),id:1,author,created_at:'2026-09-19T00:00:00Z',status:'published',version:1};posts.push(post);return json(post,201)}
    if(/\/(mine|posts)\/1$/.test(path))return json({...posts[0],pets:pets.filter(p=>posts[0].pet_ids.includes(p.id))})
    if(path.endsWith('/comments'))return json({items:[],next_cursor:null})
    if(path.endsWith('/interaction'))return json({like_count:0,comment_count:0,liked:false})
    if(path.endsWith('/posts'))return json({items:posts,next_cursor:null})
    return json({})
  })
  await page.goto('/#/pets')
  await expect(page.getByText('还没有宠物档案，添加你的第一位小伙伴吧。')).toBeVisible()
  await page.getByRole('button',{name:'添加宠物'}).click()
  await page.getByLabel('宠物名字').fill('团子')
  await page.getByLabel('种类',{exact:true}).selectOption('cat')
  await page.getByLabel('生日（选填）').fill('2020-01-01')
  await page.getByLabel('宠物照片',{exact:true}).setInputFiles({name:'pet.png',mimeType:'image/png',buffer:Buffer.from('mock')})
  await page.getByRole('button',{name:'保存宠物档案'}).click()
  await expect(page.getByRole('button',{name:'编辑 团子'})).toBeVisible()
  await page.getByRole('button',{name:'添加宠物'}).click()
  await page.getByLabel('宠物名字').fill('豆豆')
  await page.getByLabel('种类',{exact:true}).selectOption('bird')
  await page.getByRole('button',{name:'保存宠物档案'}).click()
  await page.getByRole('button',{name:'编辑 团子'}).click()
  await page.getByLabel('宠物介绍（选填）').fill('喜欢晒太阳的小伙伴')
  await page.setViewportSize({width:390,height:844})
  await expect(page.locator('.toast')).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/pet-editor-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'保存宠物档案'}).click()
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await expect(page.locator('.toast')).toHaveCount(0)
  await page.screenshot({path:'test-results/pets-mobile.png',fullPage:true})
  await page.goto('/#/publish')
  await page.getByLabel('正文').fill('今天一起晒太阳')
  await page.getByRole('checkbox',{name:'团子'}).check()
  await page.getByRole('checkbox',{name:'豆豆'}).check()
  await page.getByRole('button',{name:'发布日常',exact:true}).click()
  await expect(page).toHaveURL(/#\/my-posts\/1$/)
  expect(posts[0].pet_ids).toEqual([1,2])
  await expect(page.locator('.pet-card')).toHaveCount(2)
  await page.locator('.pet-card').filter({hasText:'团子'}).click()
  await expect(page.getByRole('heading',{name:'团子',exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:'它的日常 · 1 篇'})).toBeVisible()
  await expect(page.locator('.toast')).toHaveCount(0)
  await page.screenshot({path:'test-results/pet-detail-mobile.png',fullPage:true})
  await page.goto('/#/users/1')
  await expect(page.locator('.pet-card')).toHaveCount(2)
  await page.goto('/#/pets')
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'删除 团子'}).click()
  await expect(page.getByRole('button',{name:'编辑 团子'})).toHaveCount(0)
  await page.goto('/#/posts/1')
  await expect(page.locator('.post-body')).toHaveText('今天一起晒太阳')
  await expect(page.locator('.pet-card')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('宠物管理需要登录，游客访问失效档案可重试',async({page})=>{
  await page.route('**/api/v1/community/pets/999',route=>route.fulfill({status:404,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({detail:'宠物档案不可用'})}))
  await page.goto('/#/pets')
  await expect(page).toHaveURL(/login\?redirect=/)
  await page.goto('/#/pets/999')
  await expect(page.getByRole('alert')).toContainText('宠物档案不可用')
  await expect(page.getByRole('button',{name:'重新加载'})).toBeVisible()
})
