<script setup>
import { computed, onMounted, onBeforeUnmount, reactive, ref } from 'vue'
import { onBeforeRouteLeave } from 'vue-router'
import CommunityShell from '../components/CommunityShell.vue'
import CommunityImage from '../components/CommunityImage.vue'
import PetCards from '../components/PetCards.vue'
import { community, categories } from '../api/community.js'
import { toast } from '../composables/useToast.js'
const pets=ref([]), loading=ref(true), busy=ref(false), uploading=ref(false), error=ref(''), opened=ref(false), editing=ref(null), baseline=ref('')
const form=reactive({name:'',species:'cat',breed:'',sex:'unknown',birthday:'',bio:'',photo_id:null})
const species=Object.fromEntries(Object.entries(categories).filter(([key])=>key!=='general'))
let requestKey=''
const dirty=computed(()=>opened.value && JSON.stringify(form)!==baseline.value)
const today=new Date().toLocaleDateString('en-CA')
function leave(){return !busy.value && !uploading.value && (!dirty.value || window.confirm('宠物档案尚未保存，确定离开吗？'))}
onBeforeRouteLeave(leave)
function beforeUnload(event){if(dirty.value || busy.value || uploading.value){event.preventDefault();event.returnValue=''}}
window.addEventListener('beforeunload',beforeUnload)
onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
async function load(){loading.value=true;error.value='';try{pets.value=(await community('/me/pets')).items || []}catch(reason){error.value=reason.message}finally{loading.value=false}}
function open(pet=null){if(!leave())return;editing.value=pet;Object.assign(form,{name:pet?.name||'',species:pet?.species||'cat',breed:pet?.breed||'',sex:pet?.sex||'unknown',birthday:pet?.birthday||'',bio:pet?.bio||'',photo_id:pet?.photo_id||null});requestKey=crypto.randomUUID();baseline.value=JSON.stringify(form);opened.value=true;error.value=''}
function cancel(){if(leave())opened.value=false}
async function upload(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;error.value='';if(file.size>10*1024*1024 || !['image/jpeg','image/png','image/webp'].includes(file.type)){error.value='请选择 10 MB 以内的 JPEG、PNG 或 WebP 图片';return}uploading.value=true;try{form.photo_id=(await community('/media',{method:'POST',headers:{'Content-Type':file.type},body:file})).id}catch(reason){error.value=reason.message}finally{uploading.value=false}}
async function save(){if(busy.value||uploading.value)return;busy.value=true;error.value='';try{const body={...form,birthday:form.birthday||null,...(editing.value?{version:editing.value.version}:{request_key:requestKey})};const pet=await community(editing.value?`/me/pets/${editing.value.id}`:'/me/pets',{method:editing.value?'PUT':'POST',body:JSON.stringify(body)});pets.value=[pet,...pets.value.filter(item=>item.id!==pet.id)];opened.value=false;toast('宠物档案已保存')}catch(reason){error.value=reason.message}finally{busy.value=false}}
async function remove(pet){if(busy.value||uploading.value||!leave()||!window.confirm(`删除「${pet.name}」的档案？原帖子将保留，宠物关联会移除。`))return;busy.value=true;error.value='';try{await community(`/me/pets/${pet.id}?version=${pet.version}`,{method:'DELETE'});pets.value=pets.value.filter(item=>item.id!==pet.id);if(editing.value?.id===pet.id)opened.value=false;toast('宠物档案已删除')}catch(reason){error.value=reason.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><CommunityShell><header class="community-heading"><div><p class="overline">MY LITTLE FAMILY</p><h1>我的宠物</h1><p>每一种陪伴，都有自己的名字。</p></div><button class="c-button primary" :disabled="busy||uploading||loading" @click="open()">＋ 添加宠物</button></header><p v-if="error" class="community-error" role="alert">{{ error }} <button :disabled="busy||uploading" @click="load">刷新列表</button></p><form v-if="opened" class="pet-form" @submit.prevent="save"><h2>{{ editing ? '编辑宠物档案' : '认识新朋友' }}</h2><p class="field-hint">档案会公开展示在你的主页。每个账号最多 50 只宠物。</p><fieldset :disabled="busy||uploading"><div class="photo-row"><CommunityImage v-if="form.photo_id" :private-path="`/api/v1/community/media/${form.photo_id}?thumbnail=true`" alt="宠物照片预览" /><label class="c-button upload-label">{{ uploading?'上传中…':'选择照片' }}<input type="file" accept="image/jpeg,image/png,image/webp" aria-label="宠物照片" @change="upload" /></label><button v-if="form.photo_id" type="button" class="c-button" @click="form.photo_id=null">移除照片</button></div><p class="field-hint">照片选填，支持 JPEG / PNG / WebP，最大 10 MB。</p><div class="pet-fields"><div><label for="pet-name">宠物名字</label><input id="pet-name" v-model="form.name" maxlength="32" required /></div><div><label for="pet-species">种类</label><select id="pet-species" v-model="form.species"><option v-for="(label,key) in species" :key="key" :value="key">{{ label }}</option></select></div><div><label for="pet-breed">品种（选填）</label><input id="pet-breed" v-model="form.breed" maxlength="50" /></div><div><label for="pet-sex">性别</label><select id="pet-sex" v-model="form.sex"><option value="unknown">未知 / 不填写</option><option value="male">公</option><option value="female">母</option></select></div><div><label for="pet-birthday">生日（选填）</label><input id="pet-birthday" v-model="form.birthday" type="date" :max="today" /></div></div><label for="pet-bio">宠物介绍（选填）</label><textarea id="pet-bio" v-model="form.bio" maxlength="500" placeholder="它的性格、爱好，还有你们的故事…"></textarea></fieldset><footer><button class="c-button" type="button" :disabled="busy||uploading" @click="cancel">取消</button><button class="c-button primary" :disabled="busy||uploading">{{ busy?'保存中…':'保存宠物档案' }}</button></footer></form><p v-if="loading" class="community-empty" role="status">正在加载宠物档案…</p><p v-else-if="!pets.length && !opened && !error" class="community-empty">还没有宠物档案，添加你的第一位小伙伴吧。</p><div class="pet-management"><section v-for="pet in pets" :key="pet.id"><PetCards :pets="[pet]" /><p v-if="pet.hidden" class="field-hint">该档案已停止公开展示。修改资料后仍需管理员恢复，可在「处理记录」查看原因。</p><div class="pet-actions"><button class="c-button" :disabled="busy||uploading" @click="open(pet)">编辑 {{ pet.name }}</button><button class="c-button danger" :disabled="busy||uploading" @click="remove(pet)">删除 {{ pet.name }}</button></div></section></div></CommunityShell></template>
<style scoped>.pet-form{max-width:760px;margin:24px 0 32px;padding:28px;border:1px solid var(--line);border-radius:20px;background:white}.pet-form h2{font-size:20px;margin-bottom:12px}.pet-form fieldset{border:0;padding:0;min-width:0}.pet-fields{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:22px 0}.pet-form label:not(.upload-label){display:block;font-size:13px;margin-bottom:8px}.pet-form input:not([type=file]),.pet-form select,.pet-form textarea{width:100%;padding:12px;border:1px solid #dce5d7;border-radius:9px;background:#fafbf8;font:inherit;min-width:0}.pet-form textarea{min-height:110px;resize:vertical}.pet-form footer{display:flex;gap:12px;justify-content:flex-end;margin-top:22px}.photo-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:20px}.photo-row .community-image{width:80px;height:80px;border-radius:15px}.photo-row :deep(img){height:80px}.upload-label{position:relative;overflow:hidden}.upload-label input{position:absolute;inset:0;opacity:0;cursor:pointer}.upload-label:focus-within{outline:2px solid var(--accent)}.pet-management{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:18px}.pet-management>section{min-width:0;border:1px solid var(--line);border-radius:18px;padding:0 16px 18px;background:#fffefb}.pet-actions{display:flex;gap:8px;flex-wrap:wrap}.pet-actions button{font-size:12px;overflow-wrap:anywhere}@media(max-width:580px){.pet-form{padding:20px 15px}.pet-fields{grid-template-columns:1fr}.community-heading{align-items:flex-start}.community-heading>.c-button{padding:10px;white-space:nowrap}}</style>
